[package]
name = "decluster"
version = "0.1.0"
edition = "2021"
authors = [
    "Jonny Anderson <jonny@ail.im>"
]


[[bin]]
name = "decluster"

[dependencies]
piston = "0.53.1"
piston2d-graphics = "0.42.0"
piston_window = "0.123.0"
rand = "0.8.5"